[package]
name = "msdfgen"
version = "0.1.0"
edition = "2024"

[dependencies]
ttf-parser = "0.25.1"
lyon_geom = "1.0.16"
euclid = "0.22.11"
bitflags = "2.9.4"

[dev-dependencies]
glium = "0.36"
rand = "0.9"
